name: sample
on: [push]

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.0
      - name: Set up Ruby version
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Set up bundler
        run: gem install bundler

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Run rubocop
      - run: bundle exec rubocop

      - name: Run Rspec
      - run: bundle exec rspec
