name: sample
on: [push]

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: |
          bundle install
          bundle exec rubocop
          bundle exec rspec
