name: sample
on: [push]

jobs:
  sample:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    container:
      image: ruby:2.6.3
    steps:
      - uses: actions/checkout@v1.1.0
      - name: Set up Ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Set up bundler
        run: gem install bundler

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          sudo /etc/init.d/mysql start
          bundle exec rails db:create
          bundle exec rails db:schema:load
        env:
          RAILS_ENV: test

      - name: Run Rspec
        run: bundle exec rspec
